Верстка главной, каталога и формы
htmlacademy-adaptive/1093143-pink-24 pull request #2
Opened 2021-12-28 18:21 UTC by BeregovoyRuslan

Миксы не везде делал. Пока нет стилизации и сетки, поэтому не могу точно знать что и где будет. 
Некоторые логотипы сделал из белых серыми, чтобы было видно на белом фоне, потом верну как было.

2021-12-29 09:39 UTC, Dima-Dim requested changes

2021-12-29 09:39 UTC, Dima-Dim commented on source/index.html
> +        </table>
Не хватает закрывающегося тега div
Если IDE не подсказывает, используй https://validator.w3.org/nu/

2021-12-29 09:39 UTC, Dima-Dim commented on source/catalog.html
> +          <div class="comments__info">
Элемент `comments__info` вне блока `comments`. И далее похожая проблема.
Можешь проверять вот тут https://yoksel.github.io/html-tree/
В form.html тоже подобное нужно проверить и поправить.

2021-12-29 09:40 UTC, Dima-Dim commented
> Миксы не везде делал.

Не проблема.

>  Пока нет стилизации и сетки, поэтому не могу точно знать что и где будет.

Да, правильно.

> Некоторые логотипы сделал из белых серыми, чтобы было видно на белом фоне, потом верну как было.

Хорошо.

2022-01-05 13:56 UTC, BeregovoyRuslan commented
Правки по БЭМ во втором пулреквесте. Я первый раз по ошибке все страницы сделал в module2-task1, а нужно было index в module2-task1, а catalog и form в module2-task2, сейчас я так и сделал. Но доступ отправить тебе на проверку внутренние страницы откроется только после принятия правок по пулвеквесту из module2-task1. Если по главной все хорошо, тогда влей в мастер, чтобы мне прислать на проверку внутр страницы.

2022-01-05 13:57 UTC, BeregovoyRuslan commented
Правки по БЭМ во втором пулреквесте(на гите сейчас 2 пулреквеста ожидают). Я первый раз по ошибке все страницы сделал в module2-task1, а нужно было index в module2-task1, а catalog и form в module2-task2, сейчас я так и сделал. Но доступ отправить тебе на проверку внутренние страницы откроется только после принятия правок по пулвеквесту из module2-task1. Если по главной все хорошо, тогда влей в мастер, чтобы мне прислать на проверку внутр страницы.

5 января 2022, 15:27:07, от "Dima" ***@***.***>:


@Dima-Dim requested changes on this pull request.
Не вижу правок по БЭМ.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-01-07 16:02 UTC, merged